#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

cookbook 'apt',   git: 'https://github.com/fnichol/chef-apt'

cookbook 'git',   git: 'https://github.com/fnichol/chef-git.git'

cookbook 'build-essential'

cookbook 'rvm',   :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'postgresql',   :git => 'https://github.com/findsyou/cookbooks',   :ref => 'postgresql-improvements'

cookbook 'apt', :git => 'https://github.com/opscode-cookbooks/apt.git'

cookbook 'yum', :git => 'https://github.com/opscode-cookbooks/yum.git'

cookbook 'java', :git => 'https://github.com/opscode-cookbooks/java.git'

cookbook 'elasticsearch', :git => 'https://github.com/sebwendel/chef-elasticsearch.git'

cookbook 'mongodb', :git => 'https://github.com/sebwendel/chef-mongodb.git'

cookbook 'apache2', :git => 'https://github.com/opscode-cookbooks/apache2.git'

cookbook 'graylog2', :git => 'https://github.com/sebwendel/chef-graylog2.git'

cookbook "bluepill"
cookbook "runit"
cookbook "nginx"
cookbook "unicorn"
cookbook "imagemagick"
cookbook "openssl"
cookbook "database"
cookbook "mysql"

cookbook "nodejs",
  :git => 'https://github.com/mdxp/nodejs-cookbook'
cookbook "redis",
  :git => 'https://github.com/ctrabold/chef-redis'
